import { test, expect } from '@playwright/test'
for (const width of [390, 1280]) {
  test(`manual nomenclature and editable supplier data at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.getByRole('button', { name: /Ya tengo un producto/i }).click()
    await page.getByRole('radio', { name: 'Reventa', exact: true }).click()
    await page.getByRole('radio', { name: 'Empresa', exact: true }).click()
    await page.getByRole('radio', { name: 'Sí', exact: true }).click()
    await page.locator('#journey-sensitive-category').selectOption('none')
    await page.getByRole('button', { name: /Seguir con presupuesto/i }).click()
    await page.getByRole('radio', { name: /Tengo rango de unidades/i }).click()
    await page.getByRole('button', { name: /Seguir con el producto/i }).click()
    await page.getByRole('button', { name: /Describir el producto/i }).click()
    await page.locator('.owned-product-entry textarea').fill('Parrilla cerrada para cocinar a leña y carbón de acero')
    await page.locator('.owned-product-entry').getByRole('button', { name: 'Continuar' }).click()
    await page.getByRole('button', { name: 'Buscar o cambiar posición en el nomenclador' }).click()
    await page.getByLabel('Producto o código NCM').fill('73211900')
    await page.locator('.manual-ncm-results input[type=radio]').first().check()
    await expect(page.getByRole('button', { name: 'Usar esta posición' })).toBeDisabled()
    await page.getByLabel('Revisé la descripción y corresponde a mi producto.').check()
    await page.getByRole('button', { name: 'Usar esta posición' }).click()
    await page.getByRole('button', { name: 'Corregir un dato detectado' }).click()
    await page.getByLabel('País de origen de la mercadería').fill('China')
    await page.getByLabel('Precio FOB unitario (USD)').fill('15')
    await page.getByLabel('Peso de una unidad embalada (kg)').fill('0.18')
    await page.getByLabel('Volumen unitario, si lo sabés (m³)').fill('0.002')
    await page.getByLabel('MOQ / cantidad mínima (opcional)').fill('')
    await expect(page.getByLabel('Peso de una unidad embalada (kg)')).toHaveValue('0.18')
    await expect(page.getByRole('button', { name: /Cotizar con estos datos/ })).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
}
