import { test, expect } from './fixtures'
for (const width of [390, 1280]) {
  test(`manual nomenclature and editable supplier data at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.getByRole('button', { name: /Ya tengo un producto/i }).click()
    await page.getByRole('radio', { name: 'Reventa', exact: true }).click()
    await page.getByRole('radio', { name: 'Empresa', exact: true }).click()
    await page.getByRole('radio', { name: 'Sí', exact: true }).click()
    await page.getByRole('button', { name: /Seguir con presupuesto/i }).click()
    await page.getByRole('radio', { name: /Tengo rango de unidades/i }).click()
    await page.getByRole('button', { name: /Seguir con el producto/i }).click()
    await page.getByRole('button', { name: /Describir el producto/i }).click()
    // Chatbot flow: name → use → material (optional) → price → origin → weight → moq → skip volume
    await page.getByLabel('¿Cómo se llama el producto?').fill('Parrilla cerrada para cocinar a leña y carbón de acero')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿Para qué se usa?').fill('Para cocinar a la parrilla')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿De qué está hecho?').fill('Acero')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿Cuánto vale al proveedor? (FOB)').fill('15')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿De dónde viene?').fill('China')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿Cuánto pesa por unidad?').fill('0.18')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByLabel('¿Cuál es el mínimo del proveedor?').fill('50')
    await page.getByRole('button', { name: 'Continuar' }).click()
    await page.getByRole('button', { name: 'No sé / omitir' }).click()
    // After chatbot completes, pipeline auto-classifies (silent mode — no confirm card shown)
    await expect(page.locator('#case-confirmation')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
}
