import { test, expect } from '@playwright/test'
for (const width of [390, 1280]) {
  test(`manual nomenclature and editable supplier data at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.getByRole('button', { name: /Ya tengo un producto/i }).click()
    await page.getByRole('radio', { name: 'Reventa', exact: true }).click()
    await page.getByRole('radio', { name: 'Empresa', exact: true }).click()
    await page.getByRole('radio', { name: 'Sí', exact: true }).click()
    await page.locator('#journey-sensitive-category').selectOption('none')
    await page.getByRole('button', { name: /Seguir con presupuesto/i }).click()
    await page.getByRole('radio', { name: /Tengo rango de unidades/i }).click()
    await page.getByRole('button', { name: /Seguir con el producto/i }).click()
    await page.getByRole('button', { name: /Describir el producto/i }).click()
    await page.locator('.owned-product-entry textarea').fill('Parrilla cerrada para cocinar a leña y carbón de acero')
    await page.locator('.owned-product-entry').getByRole('button', { name: 'Continuar' }).click()
    await page.getByRole('button', { name: 'Buscar o cambiar posición en el nomenclador' }).click()
    await page.getByLabel('Producto o código NCM').fill('73211900')
    await page.locator('.manual-ncm-results input[type=radio]').first().check()
    await expect(page.getByRole('button', { name: 'Usar esta posición' })).toBeDisabled()
    await page.getByLabel('Revisé la descripción y corresponde a mi producto.').check()
    await page.getByRole('button', { name: 'Usar esta posición' }).click()
    await page.getByRole('button', { name: 'Corregir un dato detectado' }).click()
    await page.getByLabel('País de origen de la mercadería').fill('China')
    await page.getByLabel('Precio original del proveedor').fill('15')
    await page.getByLabel('Moneda original').selectOption('USD')
    await page.getByLabel('Variante / modelo / presentación').fill('única')
    await page.getByLabel('Cantidad a cotizar (unidades)').fill('75')
    await page.getByLabel('Peso de una unidad embalada (kg)').fill('0.18')
    await page.getByLabel('Volumen unitario, si lo sabés (m³)').fill('0.002')
    await page.getByLabel('MOQ / cantidad mínima (opcional)').fill('')
    await expect(page.getByLabel('Peso de una unidad embalada (kg)')).toHaveValue('0.18')
    const quote = page.getByRole('button', { name: /Cotizar con estos datos/ })
    const review = page.getByRole('checkbox', { name: /Revisé el producto, el precio/ })
    await expect(quote).toBeDisabled()
    await review.check()
    await expect(quote).toBeEnabled()
    await page.getByLabel('Precio original del proveedor').fill('16')
    await expect(review).not.toBeChecked()
    await expect(quote).toBeDisabled()
    await review.check()
    await expect(quote).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.route('**/api/analyze', route => route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"Unauthorized."}' }))
    await quote.click()
    await expect(page.getByText('Tu producto está guardado. Falta iniciar sesión.')).toBeVisible()
    await expect(page.getByRole('button', { name: /Responder lo que falta/ })).toHaveCount(0)
    await page.getByRole('button', { name: /Ya ingresé: retomar mi producto/ }).click()
    await expect(page.getByLabel('Precio original del proveedor')).toHaveValue('16')
    await expect(page.getByText('75 unidades', { exact: true })).toBeVisible()
    await expect(review).not.toBeChecked()

  })
}
