import { test, expect } from './fixtures'

async function setup(page: import('@playwright/test').Page, search = false) {
  await page.goto('/')
  await page.getByRole('button', { name: search ? /Quiero buscarlo/ : /Ya tengo un producto/ }).click()
  await page.getByRole('radio', { name: 'Reventa', exact: true }).click()
  await page.getByRole('radio', { name: 'Empresa', exact: true }).click()
  await page.getByRole('radio', { name: 'Sí', exact: true }).click()
  await page.getByRole('button', { name: /Seguir con presupuesto/ }).click()
  await page.getByRole('radio', { name: /Todavía no sé/ }).click()
  await page.getByRole('button', { name: /Seguir con el producto/ }).click()
}

test('electric motorcycle: unknown MOQ, persisted confirmation, validated manual NCM at 320px', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 320, height: 780 })
  await setup(page)
  await page.getByRole('button', { name: /Describir el producto/ }).click()
  for (const [label, value] of [
    ['¿Cómo se llama el producto?', 'Motocicleta eléctrica modelo M5 sin pedales, motor de 3000 W'],
    ['¿Para qué se usa?', 'Transporte de personas por carretera, sin asistencia de pedaleo'],
    ['¿De qué está hecho?', 'Acero y batería de litio'],
    ['¿Cuánto vale al proveedor? (FOB)', '500'],
    ['¿De dónde viene?', 'China'],
    ['¿Cuánto pesa por unidad?', '80'],
  ]) {
    await page.getByLabel(label).fill(value)
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  }
  await expect(page.getByLabel('¿Cuál es el mínimo del proveedor?')).toBeVisible()
  await page.getByRole('button', { name: 'No sé / omitir', exact: true }).click()
  await page.getByRole('button', { name: 'No sé / omitir', exact: true }).click()
  const review = page.locator('#case-confirmation')
  await expect(review).toBeVisible()
  await expect(review.locator('.pipeline-known-grid').first()).toContainText('Sin dato')
  await page.getByLabel('Variante / modelo confirmado').fill('M5 · sin pedales · 3000 W')
  await page.reload()
  await expect(page.getByLabel('Variante / modelo confirmado')).toHaveValue('M5 · sin pedales · 3000 W')
  await page.getByRole('button', { name: /Buscar o cambiar posición/ }).click()
  await page.getByLabel('Producto o código NCM').fill('8711.60.00')
  const candidate = page.getByRole('radio', { name: /8711.60.00.*motor eléctrico/ })
  await expect(candidate).toBeVisible()
  await candidate.check()
  await page.getByRole('checkbox', { name: /Revisé la descripción/ }).check()
  await page.getByRole('button', { name: 'Usar esta posición', exact: true }).click()
  await expect(review).toContainText('Posición 8711.60.00')
  await expect(page.getByLabel('O indicá una cantidad')).toHaveValue('')
  await page.getByLabel('O indicá una cantidad').fill('3')
  await expect(review).toContainText('volumen o medidas del bulto unitario')
  await expect(page.locator('.journey-calculator-section')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('electric-motorcycle-320.png'), fullPage: true })
})

test('supplier search retains successful results and query after Alibaba extraction and retry failures', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  let searches = 0
  await page.route('**/api/opportunity-search', async route => {
    searches++
    if (searches > 1) return route.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ error: 'Alibaba no respondió. Reintentá o continuá manualmente.' }) })
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ status: 'live', mode: 'parsebot', query: 'motorcycle', note: 'Publicación de prueba', constraints: { maxUnitPriceUsd: null, maxMoq: null, originCountry: null, excludedOriginCountries: [], lowMoqPreference: false }, constraintsNote: '', results: [{ title: 'Electric motorcycle M5', url: 'https://www.alibaba.com/product-detail/M5_1600000001234.html', unitPriceUsd: 500, priceDisplay: '$500 / set', moq: null }] }) })
  })
  await page.route('**/api/product-read', async route => route.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ error: 'No pude leer esta publicación de Alibaba.' }) }))
  await setup(page, true)
  const input = page.getByRole('textbox', { name: 'Buscar productos en Alibaba' })
  const query = 'Motocicleta eléctrica sin pedales modelo M5'
  await input.fill(query)
  await page.getByRole('button', { name: 'Buscar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Electric motorcycle M5' })).toBeVisible()
  await page.getByRole('button', { name: 'Usar este producto' }).click()
  await expect(page.getByRole('alert')).toContainText('No pude leer')
  await expect(page.getByRole('heading', { name: 'Electric motorcycle M5' })).toBeVisible()
  await page.getByRole('button', { name: 'Reintentar búsqueda' }).click()
  await expect(page.getByRole('alert')).toContainText('Alibaba no respondió')
  await expect(input).toHaveValue(query)
  await expect(page.getByRole('button', { name: 'Buscar', exact: true })).toBeEnabled()
  await page.reload()
  await expect(input).toHaveValue(query)
  await expect(page.getByRole('heading', { name: 'Electric motorcycle M5' })).toBeVisible()
  expect(searches).toBe(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('supplier-recovery-390.png'), fullPage: true })
})

test('ambiguous supplier currency blocks costs; documented pack conversion and tier edit recalculate', async ({ page }, testInfo) => {
  const { createManualProductAnalysis } = await import('../../src/lib/productConfirmation')
  const source = 'https://www.alibaba.com/product-detail/Tennis_1600000001234.html'
  const fixture = createManualProductAnalysis(source, 'Raqueta de tenis de aluminio')
  Object.assign(fixture.product, { category: 'Raqueta de tenis', material: 'Aluminio', functionText: 'Para jugar tenis', originCountry: 'China', unitPriceUsd: 100, moq: null, packedWeightKg: 0.5, volumeCbm: 0.01, supplierEvidence: { priceText: '$100 / box', currency: null, quantityUnit: 'box', variant: null } })
  let paidRequests = 0
  await page.route('**/api/product-read', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify(fixture) }))
  await page.route('**/api/analyze', async route => {
    paidRequests++
    const submitted = route.request().postDataJSON()
    await route.fulfill({ contentType: 'application/json', headers: { 'x-shippingapp-usage-reservation': 'fixture-reservation' }, body: JSON.stringify({ ...fixture, product: submitted.product }) })
  })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await setup(page, true)
  await page.getByRole('textbox', { name: 'Buscar productos en Alibaba' }).fill(source)
  await page.getByRole('button', { name: 'Buscar', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Moneda original' })).toContainText('Elegí la moneda')
  await page.getByRole('button', { name: /Buscar o cambiar posición/ }).click()
  await page.getByLabel('Producto o código NCM').fill('9506.51.00')
  await page.getByRole('radio', { name: /9506.51.00/ }).check()
  await page.getByRole('checkbox', { name: /Revisé la descripción/ }).check()
  await page.getByRole('button', { name: 'Usar esta posición', exact: true }).click()
  await page.getByLabel('O indicá una cantidad').fill('20')
  const confirm = page.getByRole('button', { name: /Cotizar con estos datos/ })
  await expect(confirm).toBeDisabled()
  expect(paidRequests).toBe(0)
  await page.getByRole('combobox', { name: 'Moneda original' }).click()
  await page.getByRole('option', { name: /CNY/ }).click()
  await expect(page.getByRole('combobox', { name: 'Moneda original' })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('combobox', { name: 'Precio por' }).click()
  await page.getByRole('option', { name: 'Lote / caja', exact: true }).click()
  await page.getByLabel('Unidades por lote').fill('5')
  await page.getByLabel('Variante / modelo confirmado').fill('T-5 aluminio')
  await page.getByLabel('USD por 1 CNY').fill('0.14')
  await page.getByLabel('Fecha del tipo de cambio').fill('2026-10-06')
  await expect(confirm).toBeDisabled()
  await page.getByLabel('Fuente del tipo de cambio').fill('Fuente de prueba documentada')
  await page.getByLabel('Precio válido hasta (opcional)').fill('49')
  await page.getByRole('button', { name: 'Agregar otro tramo de precio confirmado' }).click()
  await page.getByLabel('Importe original del tramo').fill('80')
  await page.getByLabel('Desde (unidades)', { exact: true }).fill('50')
  await expect(page.locator('.supplier-review')).toContainText('$2.80')
  await confirm.click()
  await expect(page.locator('.journey-calculator-section')).toBeVisible()
  await expect(page.locator('.market-estimate-lead')).toContainText('No hay evidencia suficiente')
  const initialCost = await page.locator('.result-hero-number').textContent()
  await page.locator('.quote-assumptions > summary').click()
  await page.getByRole('button', { name: 'Editar ficha del producto' }).click()
  await page.getByRole('button', { name: 'Corregir un dato detectado' }).click()
  await page.getByLabel('Cantidad a cotizar (unidades)').fill('60')
  await expect(page.locator('.supplier-review')).toContainText('$2.24')
  await confirm.click()
  await expect(page.locator('.journey-calculator-section')).toBeVisible()
  await expect(page.locator('.result-hero-number')).not.toHaveText(initialCost!)
  const saved = await page.evaluate(() => JSON.parse(sessionStorage.getItem('shippingapp:product-draft:analysis')!).data.analysis.product)
  expect(saved.purchaseQuantity).toBe(60)
  expect(saved.unitPriceUsd).toBeCloseTo(2.24)
  expect(paidRequests).toBe(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('confirmed-tier-dark-390.png'), fullPage: true })
})
