export type RouteAccess = 'public' | 'operational' | 'provider_callback' | 'provider_webhook'
export type TargetAccess = 'public' | 'authenticated' | 'internal' | 'provider_callback' | 'provider_webhook'
export type CostRisk = 'low' | 'medium' | 'high'

export type RoutePolicy = {
  id: string
  path: string
  methods: readonly string[]
  currentAccess: RouteAccess
  targetAccess: TargetAccess
  targetMetered: boolean
  costRisk: CostRisk
  externalProviders: readonly string[]
  notes: string
}

export const API_ROUTE_POLICIES: readonly RoutePolicy[] = [
  {
    id: 'image-proxy',
    path: '/api/image-proxy',
    methods: ['GET', 'HEAD'],
    currentAccess: 'public',
    targetAccess: 'public',
    targetMetered: false,
    costRisk: 'medium',
    externalProviders: ['remote product image host'],
    notes: 'Public image relay. Must retain SSRF/domain restrictions in imageProxy.',
  },
  {
    id: 'me',
    path: '/api/me',
    methods: ['GET'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: ['Clerk'],
    notes: 'Authenticated account probe. Identity is derived from verified Clerk session only; Stage 6 also syncs the server-owned primary email profile.',
  },
  {
    id: 'usage',
    path: '/api/usage',
    methods: ['GET'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped plan/usage view. Entitlement state is derived only from server-owned plans, subscriptions and usage periods.',
  },
  {
    id: 'email-preferences',
    path: '/api/email-preferences',
    methods: ['GET', 'PATCH'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped digest/alert/marketing preferences. User identity is server-derived and transactional/security mail is not client-configurable.',
  },
  {
    id: 'email-unsubscribe',
    path: '/api/email-unsubscribe',
    methods: ['GET', 'POST'],
    currentAccess: 'public',
    targetAccess: 'public',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Public signed-token unsubscribe flow. GET is confirmation-only; POST mutates only the HMAC-signed user/scope.',
  },
  {
    id: 'email-runtime',
    path: '/api/email-runtime',
    methods: ['GET'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: ['Resend'],
    notes: 'Secret-free operational status for Stage 6 email configuration and template availability.',
  },
  {
    id: 'digest-runtime',
    path: '/api/digest-runtime',
    methods: ['GET'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Aggregate-only Stage 7 scheduler state. Never returns user IDs, recipients, product titles or message bodies.',
  },
  {
    id: 'digest-dry-run',
    path: '/api/digest-dry-run',
    methods: ['POST'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Internal aggregate eligibility probe. Reads production state but sends no email and stores no recipient/content data.',
  },
  {
    id: 'analysis-history',
    path: '/api/history',
    methods: ['GET', 'POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped completed-analysis history. POST persists a completed client calculation under server-derived user identity; GET lists only that owner.',
  },
  {
    id: 'analysis-history-item',
    path: '/api/history-item',
    methods: ['GET', 'DELETE'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped history detail and soft delete. Missing and cross-tenant IDs must be indistinguishable.',
  },
  {
    id: 'watchlist',
    path: '/api/watchlist',
    methods: ['GET', 'POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped explicit follow list. POST accepts only an owned analysis ID; title/source/economic snapshot are derived server-side.',
  },
  {
    id: 'watchlist-item',
    path: '/api/watchlist-item',
    methods: ['GET', 'DELETE'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Owner-scoped watchlist detail and deactivation. Snapshot history is preserved on remove/re-add.',
  },
  {
    id: 'watchlist-refresh',
    path: '/api/watchlist-refresh',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Mercado Libre', 'Google Shopping / SerpApi', 'direct Argentine retailers'],
    notes: 'Standalone one-credit refresh in Stage 5. Server performs trusted market lookup; unusable provider evidence releases the reservation.',
  },
  {
    id: 'runtime-smoke',
    path: '/api/runtime-smoke',
    methods: ['GET'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: [],
    notes: 'Used by GitHub Actions production smoke checks. Keep response free of secrets.',
  },
  {
    id: 'alibaba-direct-probe',
    path: '/api/alibaba-direct-probe',
    methods: ['POST'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'medium',
    externalProviders: ['Alibaba'],
    notes: 'Diagnostic zero-credit HTTPS/HTML extractor. Internal-only target because it performs remote fetch work.',
  },
  {
    id: 'alibaba-native-probe',
    path: '/api/alibaba-native-probe',
    methods: ['POST'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'high',
    externalProviders: ['Cloudflare Browser / Alibaba'],
    notes: 'Diagnostic route that deliberately bypasses Parse.bot. Must not remain a public production compute surface.',
  },
  {
    id: 'mercadolibre-oauth-callback',
    path: '/oauth/mercadolibre/callback',
    methods: ['GET'],
    currentAccess: 'provider_callback',
    targetAccess: 'provider_callback',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: ['Mercado Libre'],
    notes: 'Bootstrap/admin OAuth callback; authorization codes are sensitive and must never be logged.',
  },
  {
    id: 'mercadolibre-api-callback-alias',
    path: '/api/mercadolibre/callback',
    methods: ['GET'],
    currentAccess: 'provider_callback',
    targetAccess: 'provider_callback',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: ['Mercado Libre'],
    notes: 'Legacy callback alias. Candidate for removal once production OAuth flow is finalized.',
  },
  {
    id: 'mercadolibre-notifications',
    path: '/api/mercadolibre/notifications',
    methods: ['GET', 'POST'],
    currentAccess: 'provider_webhook',
    targetAccess: 'provider_webhook',
    targetMetered: false,
    costRisk: 'low',
    externalProviders: ['Mercado Libre'],
    notes: 'Currently acknowledges notifications without processing them. Future processing must verify authenticity/idempotency.',
  },
  {
    id: 'mercadolibre-status',
    path: '/api/mercadolibre/status',
    methods: ['GET'],
    currentAccess: 'operational',
    targetAccess: 'internal',
    targetMetered: false,
    costRisk: 'medium',
    externalProviders: ['Mercado Libre'],
    notes: 'Performs authenticated identity check; intended for operations, not end users.',
  },
  {
    id: 'mercadolibre-benchmark',
    path: '/api/mercadolibre/benchmark',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'medium',
    externalProviders: ['Mercado Libre'],
    notes: 'Standalone one-credit Mercado Libre benchmark in Stage 5; insufficient provider evidence releases the reservation.',
  },
  {
    id: 'argentina-market-benchmark',
    path: '/api/argentina-market/benchmark',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Mercado Libre', 'Google Shopping / SerpApi'],
    notes: 'Standalone one-credit hybrid Argentina benchmark. Reservation occurs before external providers and settles only on live evidence.',
  },
  {
    id: 'chat',
    path: '/api/chat',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: false,
    costRisk: 'medium',
    externalProviders: ['Cloudflare Workers AI'],
    notes: 'Conversational Import Analyst. Authenticated but intentionally zero-credit in the current Stage 5 product policy.',
  },
  {
    id: 'intake',
    path: '/api/intake',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Cloudflare Workers AI', 'Mercado Libre', 'BCRA'],
    notes: 'Starts a one-credit full-analysis reservation. The same reservation covers the subsequent NCM continuation; clarification-only responses release it.',
  },
  {
    id: 'opportunity-search',
    path: '/api/opportunity-search',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Parse.bot / Alibaba'],
    notes: 'Standalone one-credit external Alibaba opportunity search.',
  },
  {
    id: 'discover',
    path: '/api/discover',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Cloudflare Browser / Alibaba'],
    notes: 'Standalone one-credit live Alibaba browser discovery.',
  },
  {
    id: 'ncm-classify',
    path: '/api/ncm-classify',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'medium',
    externalProviders: ['Cloudflare Workers AI'],
    notes: 'Zero-additional-credit continuation of a reserved /api/analyze or /api/intake full analysis. The reservation/product identity is verified before provider work.',
  },
  {
    id: 'analyze',
    path: '/api/analyze',
    methods: ['POST'],
    currentAccess: 'public',
    targetAccess: 'authenticated',
    targetMetered: true,
    costRisk: 'high',
    externalProviders: ['Parse.bot / Alibaba', 'ShippingAPP direct Alibaba', 'Cloudflare Browser', 'Cloudflare Workers AI', 'Mercado Libre', 'BCRA'],
    notes: 'Starts a one-credit full-analysis reservation. The same reservation covers the subsequent NCM continuation and settles only after that continuation succeeds.',
  },
] as const

export function resolveRoutePolicy(pathname: string, method: string) {
  const normalizedMethod = method.toUpperCase()
  return API_ROUTE_POLICIES.find((route) => route.path === pathname && route.methods.includes(normalizedMethod)) ?? null
}
